name: Build Magisk OverlayFS Module

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
          unzip android-ndk-r23b-linux.zip -d android-ndk

      - name: Run build script
        run: |
          bash build.sh
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: magisk_overlayfs_module
          path: out/*.zip
